"""Status constants for SRM Core lifecycle logic."""

INCIDENT_DRAFT = "Draft"
INCIDENT_OPEN = "Open"
INCIDENT_UNDER_INVESTIGATION = "Under Investigation"
INCIDENT_RESOLVED = "Resolved"
INCIDENT_CLOSED = "Closed"

INCIDENT_TERMINAL_STATUSES = (INCIDENT_RESOLVED, INCIDENT_CLOSED)
INCIDENT_RESOLUTION_REQUIRED_STATUSES = (INCIDENT_RESOLVED, INCIDENT_CLOSED)

VALID_INCIDENT_STATUSES = frozenset(
	{
		INCIDENT_DRAFT,
		INCIDENT_OPEN,
		INCIDENT_UNDER_INVESTIGATION,
		INCIDENT_RESOLVED,
		INCIDENT_CLOSED,
	}
)

INVESTIGATION_OPEN = "Open"
INVESTIGATION_PENDING_EVIDENCE = "Pending Evidence"
INVESTIGATION_COMPLETED = "Completed"
INVESTIGATION_CLOSED = "Closed"

INVESTIGATION_COMPLETION_STATUSES = (INVESTIGATION_COMPLETED, INVESTIGATION_CLOSED)
