# Copyright (c) 2026, Chibase Consulting and contributors
# For license information, please see license.txt

from frappe.model.document import Document
from frappe import logger


class ImpactSnapshot(Document):
	"""Read-only snapshot of progress toward a target.
	
	Generated by calculation engine, not directly editable.
	"""

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self._allow_save = False

	def save(self, *args, **kwargs):
		"""Snapshots are generated only by the calculation engine, not edited by users."""
		if not self._allow_save:
			logger().warning(
				f"Attempted manual edit of ImpactSnapshot {self.name}. Snapshots are read-only."
			)
			return
		super().save(*args, **kwargs)
